_base_ = './oln_box.py'

classes = ('Accordion',
'Adhesive tape',
'Aircraft',
'Alarm clock',
'Alpaca',
'Ambulance',
'Animal',
'Ant',
'Antelope',
'Apple',
'Armadillo',
'Artichoke',
'Auto part',
'Axe',
'Backpack',
'Bagel',
'Baked goods',
'Balance beam',
'Ball (Object)',
'Balloon',
'Banana',
'Band-aid',
'Banjo',
'Barge',
'Barrel',
'Baseball bat',
'Baseball glove',
'Bat (Animal)',
'Bathroom accessory',
'Bathroom cabinet',
'Bathtub',
'Beaker',
'Bear',
'Beard',
'Bed',
'Bee',
'Beehive',
'Beer',
'Beetle',
'Bell pepper',
'Belt',
'Bench',
'Bicycle',
'Bicycle helmet',
'Bicycle wheel',
'Bidet',
'Billboard',
'Billiard table',
'Binoculars',
'Bird',
'Blender',
'Blue jay',
'Boat',
'Bomb',
'Book',
'Bookcase',
'Boot',
'Bottle',
'Bottle opener',
'Bow and arrow',
'Bowl',
'Bowling equipment',
'Box',
'Boy',
'Brassiere',
'Bread',
'Briefcase',
'Broccoli',
'Bronze sculpture',
'Brown bear',
'Building',
'Bull',
'Burrito',
'Bus',
'Bust',
'Butterfly',
'Cabbage',
'Cabinetry',
'Cake',
'Cake stand',
'Calculator',
'Camel',
'Camera',
'Can opener',
'Canary',
'Candle',
'Candy',
'Cannon',
'Canoe',
'Cantaloupe',
'Car',
'Carnivore',
'Carrot',
'Cart',
'Cassette deck',
'Castle',
'Cat',
'Cat furniture',
'Caterpillar',
'Cattle',
'Ceiling fan',
'Cello',
'Centipede',
'Chainsaw',
'Chair',
'Cheese',
'Cheetah',
'Chest of drawers',
'Chicken',
'Chime',
'Chisel',
'Chopsticks',
'Christmas tree',
'Clock',
'Closet',
'Clothing',
'Coat',
'Cocktail',
'Cocktail shaker',
'Coconut',
'Coffee (drink)',
'Coffee cup',
'Coffee table',
'Coffeemaker',
'Coin',
'Common fig',
'Common sunflower',
'Computer keyboard',
'Computer monitor',
'Computer mouse',
'Container',
'Convenience store',
'Cookie',
'Cooking spray',
'Corded phone',
'Cosmetics',
'Couch',
'Countertop',
'Cowboy hat',
'Crab',
'Cream',
'Cricket ball',
'Crocodile',
'Croissant',
'Crown',
'Crutch',
'Cucumber',
'Cupboard',
'Curtain',
'Cutting board',
'Dagger',
'Dairy Product',
'Deer',
'Desk',
'Dessert',
'Diaper',
'Dice',
'Digital clock',
'Dinosaur',
'Dishwasher',
'Dog',
'Dog bed',
'Doll',
'Dolphin',
'Door',
'Door handle',
'Doughnut',
'Dragonfly',
'Drawer',
'Dress',
'Drill (Tool)',
'Drink',
'Drinking straw',
'Drum',
'Duck',
'Dumbbell',
'Eagle',
'Earring',
'Egg',
'Elephant',
'Envelope',
'Eraser',
'Face powder',
'Facial tissue holder',
'Falcon',
'Fashion accessory',
'Fast food',
'Fax',
'Fedora',
'Filing cabinet',
'Fire hydrant',
'Fireplace',
'Fish',
'Fixed-wing aircraft',
'Flag',
'Flashlight',
'Flower',
'Flowerpot',
'Flute',
'Flying disc',
'Food',
'Food processor',
'Football',
'Football helmet',
'Footwear',
'Fork',
'Fountain',
'Fox',
'French fries',
'French horn',
'Frog',
'Fruit',
'Frying pan',
'Furniture',
'Garden Asparagus',
'Gas stove',
'Giraffe',
'Girl',
'Glasses',
'Glove',
'Goat',
'Goggles',
'Goldfish',
'Golf ball',
'Golf cart',
'Gondola',
'Goose',
'Grape',
'Grapefruit',
'Grinder',
'Guacamole',
'Guitar',
'Hair dryer',
'Hair spray',
'Hamburger',
'Hammer',
'Hamster',
'Hand dryer',
'Handbag',
'Handgun',
'Harbor seal',
'Harmonica',
'Harp',
'Harpsichord',
'Hat',
'Headphones',
'Heater',
'Hedgehog',
'Helicopter',
'Helmet',
'High heels',
'Hiking equipment',
'Hippopotamus',
'Home appliance',
'Honeycomb',
'Horizontal bar',
'Horse',
'Hot dog',
'House',
'Houseplant',
'Human arm',
'Human body',
'Human ear',
'Human eye',
'Human face',
'Human foot',
'Human hair',
'Human hand',
'Human head',
'Human leg',
'Human mouth',
'Human nose',
'Humidifier',
'Ice cream',
'Indoor rower',
'Infant bed',
'Insect',
'Invertebrate',
'Ipod',
'Isopod',
'Jacket',
'Jacuzzi',
'Jaguar (Animal)',
'Jeans',
'Jellyfish',
'Jet ski',
'Jug',
'Juice',
'Kangaroo',
'Kettle',
'Kitchen & dining room table',
'Kitchen appliance',
'Kitchen knife',
'Kitchen utensil',
'Kitchenware',
'Kite',
'Knife',
'Koala',
'Ladder',
'Ladle',
'Ladybug',
'Lamp',
'Land vehicle',
'Lantern',
'Laptop',
'Lavender (Plant)',
'Lemon (plant)',
'Leopard',
'Light bulb',
'Light switch',
'Lighthouse',
'Lily',
'Limousine',
'Lion',
'Lipstick',
'Lizard',
'Lobster',
'Loveseat',
'Luggage and bags',
'Lynx',
'Magpie',
'Mammal',
'Man',
'Mango',
'Maple',
'Maraca',
'Marine invertebrates',
'Marine mammal',
'Measuring cup',
'Mechanical fan',
'Medical equipment',
'Microphone',
'Microwave oven',
'Milk',
'Miniskirt',
'Mirror',
'Missile',
'Mixer',
'Mixing bowl',
'Mobile phone',
'Monkey',
'Moths and butterflies',
'Motorcycle',
'Mouse',
'Muffin',
'Mug',
'Mule',
'Mushroom',
'Musical instrument',
'Musical keyboard',
'Nail (Construction)',
'Necklace',
'Nightstand',
'Oboe',
'Office building',
'Office supplies',
'Orange (fruit)',
'Organ (Musical Instrument)',
'Ostrich',
'Otter',
'Oven',
'Owl',
'Oyster',
'Paddle',
'Palm tree',
'Pancake',
'Panda',
'Paper cutter',
'Paper towel',
'Parachute',
'Parking meter',
'Parrot',
'Pasta',
'Pastry',
'Peach',
'Pear',
'Pen',
'Pencil case',
'Pencil sharpener',
'Penguin',
'Perfume',
'Person',
'Personal care',
'Personal flotation device',
'Piano',
'Picnic basket',
'Picture frame',
'Pig',
'Pillow',
'Pineapple',
'Pitcher (Container)',
'Pizza',
'Pizza cutter',
'Plant',
'Plastic bag',
'Plate',
'Platter',
'Plumbing fixture',
'Polar bear',
'Pomegranate',
'Popcorn',
'Porch',
'Porcupine',
'Poster',
'Potato',
'Power plugs and sockets',
'Pressure cooker',
'Pretzel',
'Printer',
'Pumpkin',
'Punching bag',
'Rabbit',
'Raccoon',
'Racket',
'Radish',
'Ratchet (Device)',
'Raven',
'Rays and skates',
'Red panda',
'Refrigerator',
'Remote control',
'Reptile',
'Rhinoceros',
'Rifle',
'Ring binder',
'Rocket',
'Roller skates',
'Rose',
'Rugby ball',
'Ruler',
'Salad',
'Salt and pepper shakers',
'Sandal',
'Sandwich',
'Saucer',
'Saxophone',
'Scale',
'Scarf',
'Scissors',
'Scoreboard',
'Scorpion',
'Screwdriver',
'Sculpture',
'Sea lion',
'Sea turtle',
'Seafood',
'Seahorse',
'Seat belt',
'Segway',
'Serving tray',
'Sewing machine',
'Shark',
'Sheep',
'Shelf',
'Shellfish',
'Shirt',
'Shorts',
'Shotgun',
'Shower',
'Shrimp',
'Sink',
'Skateboard',
'Ski',
'Skirt',
'Skull',
'Skunk',
'Skyscraper',
'Slow cooker',
'Snack',
'Snail',
'Snake',
'Snowboard',
'Snowman',
'Snowmobile',
'Snowplow',
'Soap dispenser',
'Sock',
'Sofa bed',
'Sombrero',
'Sparrow',
'Spatula',
'Spice rack',
'Spider',
'Spoon',
'Sports equipment',
'Sports uniform',
'Squash (Plant)',
'Squid',
'Squirrel',
'Stairs',
'Stapler',
'Starfish',
'Stationary bicycle',
'Stethoscope',
'Stool',
'Stop sign',
'Strawberry',
'Street light',
'Stretcher',
'Studio couch',
'Submarine',
'Submarine sandwich',
'Suit',
'Suitcase',
'Sun hat',
'Sunglasses',
'Surfboard',
'Sushi',
'Swan',
'Swim cap',
'Swimming pool',
'Swimwear',
'Sword',
'Syringe',
'Table',
'Table tennis racket',
'Tablet computer',
'Tableware',
'Taco',
'Tank',
'Tap',
'Tart',
'Taxi',
'Tea',
'Teapot',
'Teddy bear',
'Telephone',
'Television',
'Tennis ball',
'Tennis racket',
'Tent',
'Tiara',
'Tick',
'Tie',
'Tiger',
'Tin can',
'Tire',
'Toaster',
'Toilet',
'Toilet paper',
'Tomato',
'Tool',
'Toothbrush',
'Torch',
'Tortoise',
'Towel',
'Tower',
'Toy',
'Traffic light',
'Traffic sign',
'Train',
'Training bench',
'Treadmill',
'Tree',
'Tree house',
'Tripod',
'Trombone',
'Trousers',
'Truck',
'Trumpet',
'Turkey',
'Turtle',
'Umbrella',
'Unicycle',
'Van',
'Vase',
'Vegetable',
'Vehicle',
'Vehicle registration plate',
'Violin',
'Volleyball (Ball)',
'Waffle',
'Waffle iron',
'Wall clock',
'Wardrobe',
'Washing machine',
'Waste container',
'Watch',
'Watercraft',
'Watermelon',
'Weapon',
'Whale',
'Wheel',
'Wheelchair',
'Whisk',
'Whiteboard',
'Willow',
'Window',
'Window blind',
'Wine',
'Wine glass',
'Wine rack',
'Winter melon',
'Wok',
'Woman',
'Wood-burning stove',
'Woodpecker',
'Worm',
'Wrench',
'Zebra',
'Zucchini',
)

# Dataset
dataset_type = 'CocoSplitDataset'
data_root = 'data/oi7/'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=16,
    workers_per_gpu=0,
    train=dict(
        is_class_agnostic=True,
        train_class='all',
        eval_class='all',
        classes=classes,
        type=dataset_type,
        img_prefix=data_root + 'images',
        pipeline=train_pipeline,
        ann_file=data_root + 'annotations/detection_train.json',
    ),
    val=dict(
        type=dataset_type,
        classes=classes,
        is_class_agnostic=True,
        ann_file=data_root + 'annotations/detection_validation.json',
        img_prefix=data_root + 'images',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        is_class_agnostic=True,
        ann_file=data_root + 'annotations/detection_test.json',
        img_prefix=data_root + 'images',
        pipeline=test_pipeline))

optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=26000,
    warmup_ratio=1.0 / 64,
    step=[7])
total_epochs = 8

checkpoint_config = dict(interval=2)
# yapf:disable
log_config = dict(
    interval=10,
    hooks=[
        dict(type='TextLoggerHook'),
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
resume_from = None
workflow = [('train', 1)]

work_dir = './work_dirs/oln_box_oi7/'
